services:
  web:
    image: jobsleads
    ports:
      - 8000:8000
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
  db:
    build: .
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khadidja
      POSTGRES_DB: jobsleads
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - djangonetwork
      
networks:
      djangonetwork:
          driver: bridge
volumes:
  data: